@host = https://sl0jjaozm9.execute-api.ap-southeast-1.amazonaws.com

###
GET {{host}}

###
# Get all users
GET {{host}}/users

###
# Get a single user
GET {{host}}/users/c13a847a-32a0-4fc9-9e66-33f6cf2a4e23

###
# Create a User
POST {{host}}/users
Content-Type: application/json

{
    "name": "kamrunnaher kanan",
    "email": "kanan@gmail.com"
}

###
# Delete a user
DELETE {{host}}/users/c13a847a-32a0-4fc9-9e66-33f6cf2a4e23


###
# Update a user data
PATCH {{host}}/users/c13a847a-32a0-4fc9-9e66-33f6cf2a4e23
Content-Type: application/json

{
    "name": "Arafat Ali",
    "email": "ali@email.com"
}