service: nifty-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  architecture: x86_64
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-1'}
  memorySize: 512
  logRetentionInDays: 1
  timeout: 15

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi:
          method: any
          path: /{proxy+}

plugins:
  - serverless-jetpack
  - serverless-offline
  - serverless-iam-roles-per-function