service: nifty-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  architecture: x86_64
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-1'}
  memorySize: 512
  logRetentionInDays: 1
  timeout: 15
  environment:
     DYNAMODB_TABLE_NAME: ${self:custom.userTableName}

custom:
  userTableName: users-table-${self:provider.stage}

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi:
          method: any
          path: /{proxy+}

resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.userTableName}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-jetpack
  - serverless-offline
  - serverless-iam-roles-per-function